### ISSUE TITLE
Errors using mute and snapshot functionality

### ISSUE THREAD

**Issue by garageboxnv** [rsnodgrass/hass-xantech#4]
I have a xantech multi zone amplifier hooked up to my home assistant instance and noticed the mute and snapshot functionality is not working.

Looking quickly into the issue thread it seems that it uses some deprecated functions. As the xantech integration is derived from the monoprice I looked into that one and saw that there new functions are called.

`Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/xantech/media_player.py:158
Integration: Xantech Multi-Zone Amps (documentation)
First occurred: 16:41:52 (1 occurrences)
Last logged: 16:41:52

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'EntityPlatform' object has no attribute 'extract_from_service'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/home/homeassistant/.homeassistant/custom_components/xantech/media_player.py", line 158, in async_service_call_dispatcher
    entities = platform.extract_from_service(service_call)
AttributeError: 'EntityPlatform' object has no attribute 'extract_from_service'`

**Comment by kbrown01** [comment]
Same issue here. Although I have a "hacked" version of this to integrate the Dayton Audio DAX88 device. Had to change some pyxantech code and I added a "dayton.yaml" protocol and a "dax88" series. I get the same errors as you do for mute and snashot although I would not really use snapshot.

At the moment I an using turn off for all the zones to "mute"

**Comment by kbrown01** [comment]
Maybe this should be:

async def async_service_call_dispatcher(service_call):
        entities = await async_platform.extract_from_service(service_call)

**Comment by kbrown01** [comment]
As for mute, the self._amp.set_mute is missing await, it should be:

```
    async def async_mute_volume(self, mute):
        """Mute (true) or unmute (false) media player."""
        LOG.debug(f"Setting mute={mute} for zone {self.zone_info}")
        **await** self._amp.set_mute(self._zone_id, mute)
```

**Comment by rsnodgrass** [comment]
> I have a xantech multi zone amplifier hooked up to my home assistant instance and noticed the mute and snapshot functionality is not working. 
> Looking quickly into the issue thread it seems that it uses some deprecated functions. As the xantech integration is derived from the monoprice I looked into that one and saw that there new functions are called.
> 
> `"/home/homeassistant/.homeassistant/custom_components/xantech/media_player.py", line 158, in async_service_call_dispatcher entities = platform.extract_from_service(service_call) AttributeError: 'EntityPlatform' object has no attribute 'extract_from_service'`

Could you contribute a Pull Request with recommended changes? Or, at lease, a link to the monoprice impl and what changed so we can get this fixed?  Thanks.

FYI, the set_mute() API that was missing await has been resolved in latest commit.

**Comment by rsnodgrass** [comment]
FYI, I believe all this needed was to call the correct async interface, making this change:

```python
-        entities = platform.extract_from_service(service_call)
+        entities = await platform.async_extract_from_service(service_call)
```

**Comment by rsnodgrass** [comment]
@garageboxnv @kbrown01 this SHOULD all be working with the latest release 0.0.9, but I have no way to test this right now. I'm going to mark this issue closed, but if it is still an issue please reopen!

**Comment by kbrown01** [comment]
I can get to it next week. That you very much!

**Comment by garageboxnv** [comment]
@rsnodgrass I updated to 0.0.9 remotely, I get following error in home-assistant.log
`Invalid key 'zone_status_skip' in dictionary 'xantech8'; returning None`

I will test the functionality later this week

Thx for fixing, I had this on my backlog to look at it

**Comment by kbrown01** [comment]
I have it running in my system for the Dayton Audio Dax88 with the one change I mentioned in another issue.
